[release] Final tweaks to release script

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -4,13 +4,11 @@
 set -o errexit
 set -o pipefail
 
-export MIX_QUIET=true
-
 #
 # Ensure semver is available (https://github.com/fsaintjacques/semver-tool/blob/master/src/semver)
 #
 echo -n "Checking for semver... "
-if [ ! $(which semver) ]; then
+if [ ! "$(which semver)" ]; then
   echo -e "🚫\\n'semver' is not available."
   exit 1
 fi
@@ -26,15 +24,15 @@ if [[ ! $1 =~ ^(patch|minor|major|release)$ ]]; then
 fi
 echo "✅"
 
-GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
-NEW_VERSION=$(semver bump $1 $(cat VERSION))
+NEW_VERSION="$(semver bump "$1" "$(cat VERSION)")"
+HEX_USER="$(mix hex.user whoami)"
 
 #
-# Only allow releases to happen in clean master branches
+# Verify correct hex auth user
 #
-echo -n "Checking for git master branch... "
-if [ ! $GIT_BRANCH == "master" ]; then
-  echo -e "🚫\\nReleases should only happen from the master branch. You have '$GIT_BRANCH' checked out."
+echo -n "Executing release as hex user '$HEX_USER'... "
+if [ ! "$HEX_USER" == "vigetlabs" ]; then
+  echo -e "🚫\\nYou must been authed with hex as the 'vigetlabs' user in order to release colonel_kurtz_ex. Please run 'mix hex.user auth' and log in."
   exit 1
 fi
 echo "✅"
@@ -42,18 +40,36 @@ echo "✅"
 #
 # Confirm release
 #
-read -p "> Are you sure you want to bump the $1 version and release '$NEW_VERSION'? (y/n) " CHOICE
+read -rp "> Are you sure you want to bump the $1 version and release '$NEW_VERSION'? (y/n) " CHOICE
 case "$CHOICE" in
   n|N ) echo "Release cancelled" && exit 1;;
   y|Y ) ;;
   * ) echo "Invalid response." && exit 1;;
 esac
 
+GIT_SHA=$(git rev-parse HEAD)
+GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+
 #
-# Ensure formatting is up to date
+# Only allow releases to happen in clean master branches
 #
-echo -n "Running 'mix format'... "
-mix format --check-formatted
+echo -n "Checking for git master branch... "
+if [ ! "$GIT_BRANCH" == "master" ]; then
+  echo -e "🚫\\nReleases should only happen from the master branch. You have '$GIT_BRANCH' checked out."
+  exit 1
+fi
+echo "✅"
+
+#
+# Ensure master is up to date with remote master
+#
+echo -n "Pulling latest master branch... "
+git pull origin master -q
+
+if [ ! "$GIT_SHA" == "$(git rev-parse HEAD)" ]; then
+  echo -e "🚫\\nPulled new changes from remote master, please verify and restart the release process."
+  exit 1
+fi
 echo "✅"
 
 #
@@ -66,20 +82,33 @@ if [[ -n $(git status -s) ]]; then
 fi
 echo "✅"
 
+# silence mix command output
+export MIX_QUIET=true
+
+#
+# Ensure formatting is up to date
+#
+echo -n "Running 'mix format'... "
+mix format --check-formatted || \
+echo -e "\\n🚫 Mix formatting is out of sync. Run 'mix format', commit the results, and restart the release." && \
+exit 1
+echo "✅"
+
 #
 # Run checks (credo, dialyzer, test)
 #
 echo -n "Running mix checks... "
 mix credo --strict && \
 mix test && \
-mix types --quiet || echo -e "🚫 One or more mix checks failed." && exit 1
+mix types --quiet || echo -e "🚫 One or more mix checks failed." && \
+exit 1
 echo "✅"
 
 #
 # Bump version number
 #
 echo -n "Bumping $1 version... "
-echo $NEW_VERSION > VERSION
+echo "$NEW_VERSION" > VERSION
 echo "✅"
 
 #
@@ -97,7 +126,7 @@ echo "✅ Docs updated and committed"
 # Create new git tag
 #
 echo "Tagging $NEW_VERSION for release..."
-git tag -a $NEW_VERSION -m "[release] Add tag for $NEW_VERSION"
+git tag -a "$NEW_VERSION" -m "[release] Add tag for $NEW_VERSION"
 git push origin master --tags
 echo "✅ Tagged release and pushed up the master branch"
 
